# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"kitty" = "ï„ "
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"thunderbird" = "ï›­"
"chrome" = "ï‰¨"
"file manager" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"bash" = "ï„ "
"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"remmina" = "ï‘³"
"microsoft teams" = "ï¡±"
"element" = "ï¡¨"
"discord" = "ï„›"
"obsidian" = "ïƒ¶"
"qutebrowser" = "ï’ˆ"

[other]
"fallback_icon" = "ğŸ¤¨"
